#!/bin/bash

init() {
    if [ -e venv ]; then
        rm -rf venv
    fi
    virtualenv venv
    venv/bin/pip install -r src/requirements.txt
}

start_app() {
    cd src
    
    ../venv/bin/python app.py &> ../working/log
    while [ -e ../working/RELOAD ]; do
        sleep 5
        echo "$(date) RESTARTING" >> ../working/log
        ../venv/bin/python app.py >> ../working/log  2>&1
    done
}


start() {
        if [ ! -e venv ]; then
            init
        fi
        if [ "$APP_ENV" == "dev" ]; then
            touch working/RELOAD
        fi
        start_app
        if [ -e working/RELOAD ]; then
            rm working/RELOAD
        fi
}

mkdir -p working

case "$1" in 
    dev)
        APP_ENV=dev
        start
        ;;
    start)
        start
        ;;
    init)
        init
        ;;
    clean)
        rm -rf venv
        rm -rf working
        ;;
    *)
        echo "Unknown option. Valid options: start init dev clean"
        exit 1
        ;;
esac
